name: Despliegue

on:
  push:
    branches:
      - main
      - actions

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [17.x]
     
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
    
      - name: Configuration of Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
         node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run : npm install

      - name: Run the tests  
        run: npm test 

      - name: Builds
        run: npm run build

      - name: Registry github user
        run: |
            git config --global user.name nicominue
            git config --global user.email nicominue@gmail.com
            git remote set-url origin https://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@github.com/nicominue/my-product-list"
      - name: Deploy   
        run: npm run deploy   
        # env:
        #  user_name: 'github-actions[bot]'
        #  user_email: 'github-actions[bot]@users.noreply.github.com'
        #  GH_TOKEN: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
        #  repository: ${{ github.repository }}
            

